### ISSUE TITLE
Vise kontaktlærer til elev i kontaktkortet

### ISSUE THREAD

**Issue by bjornkaarstein** [vtfk/dust-web#76]
Eller et annet fornuftig sted om vi tror at det kan bli utfordringer med plass. Noen ganger finnes det flere kontaktlærere. Kan være en egen test under ViS kanskje -> Kontaktlærer [Lektor Tørdal] er funnet

**Comment by runely** [comment]
Utsettes til ViS er innført

**Comment by runely** [comment]
Det er lagt på en test i `ViS` systemet som henter og viser elevens kontaktlærere (om noen) : https://github.com/vtfk/azf-dust-api/commit/1ea740da3c8e298e09d5c2b898005c2a623035a2

Det er i samme testen også lagt på å hente hvilke klasser en lærer er kontaktlærer i (om noen) : https://github.com/vtfk/azf-dust-api/commit/42cd05f94d2f2624e5d06ed7eb677fedff551dda
